# Generated by Django 5.2 on 2025-04-16 17:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=core.models.generate_uid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('date', models.DateField()),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=16)),
                ('rate_naira', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total_naira', models.DecimalField(decimal_places=2, max_digits=16)),
                ('matched_buy_ids', models.JSONField(blank=True, null=True)),
                ('gain_naira', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gain_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
