# Generated by Django 5.2 on 2025-05-08 17:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=core.models.generate_uid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('naira_rate_used_in_transation', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_used', models.BooleanField(default=False)),
                ('gain_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('used_buy_info', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
