# Generated by Django 5.2 on 2025-04-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='total_naira',
        ),
    ]
