# Generated by Django 5.2 on 2025-04-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_transaction_total_naira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='matched_buy_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
